version: "3.8"
services:
  client:
    image: node:18.15.0-alpine3.17
    working_dir: /usr/src/app
    ports:
      - ${LOCAL_PORT}:${LOCAL_PORT}
    volumes:
      - ".:/usr/src/app"
    command: sh -c "npm ci; npm run dev"
